### ISSUE TITLE
Update Lint Commit Messages link

### ISSUE THREAD

**Issue by mattgreg** [build-trust/ockam-website#125]
When the `Lint Commit Messages` runs it's check in the Azure DevOps pipeline, there is a `Get Help: {url}` message on line 20. The current URL directs the user to a github.com/ property for help. We need to replace this URL with a link to https://www.ockam.io/learn/guides/contributions/CONTRIBUTING/. 

An example of the message: 
https://dev.azure.com/ockam-network/ockam/_build/results?buildId=1439&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=efa2bfe1-554a-50c8-79b6-ef106ad3c7c2&l=27

**Comment by mrinalwadhwa** [comment]
the github links come from commitlint, the tool that is used to lint the messages. We can't change that, but we can probably do something to improve the output but changing the script here

https://github.com/ockam-network/website/blob/master/CI-pipeline.yml#L18-L24

**Comment by miedziak** [comment]
@Necromos it looks like some DevOps knowledge would be helpful here... Do you have any idea how we can improve this error message:
https://dev.azure.com/ockam-network/ockam/_build/results?buildId=1439&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=efa2bfe1-554a-50c8-79b6-ef106ad3c7c2&l=27
 in case of linting error, to make it more user friendly for ockam contributors ( link to ockam guides pasted by Matt ? )
