### ISSUE TITLE
Trigger CI/CD checks in PRs

### ISSUE THREAD

**Issue by mattgreg** [build-trust/ockam-website#157]
CD/CD checks should happen prior to merging branches into the develop branch.

Create triggers/actions that check that a PR will pass our build pipeline when a PR is opened.

**Comment by miedziak** [comment]
@Necromos I think it comes down to same steps that happends in CI, except:
- deploying to bucket/cdn.

It looks like all this PRs check we lunch thrue `CI-pipeline.yml`, should we merge it somehow with `azure-pipelines.yml`... what's your thoughts about it ?

The one `gotcha` is that we are updating algolia indexes while lunching build for `PRODUCTION` stage...
