### ISSUE TITLE
"Redirect to home page" on 404 should cancel on navigation (or go away entirely)

### ISSUE THREAD

**Issue by njvrzm** [build-trust/ockam-website#333]
If you land on a missing page, you're redirected to the main page after five seconds. This happens even if you navigate to another page first, which is very frustrating.

At the very least, the redirect should be canceled if you navigate to another page, but I would consider removing the redirect entirely and instead showing some suggested links or an abbreviated site map.

**Comment by Necromos** [comment]
recheckcla
