### ISSUE TITLE
Documentation link under 'Contact Us' routes to the wrong URL

### ISSUE THREAD

**Issue by Ippolito72** [build-trust/ockam-website#596]
In the Contact Us section of the website, the documentation link routes to the Ockam blog instead of https://docs.ockam.io/

<img width="385" alt="Screen Shot 2022-08-16 at 10 52 52 AM" src="https://user-images.githubusercontent.com/67592293/184910588-98a83770-d75a-41ea-bd88-a231f750ee06.png">

**Comment by mrinalwadhwa** [comment]
@Ippolito72 thank you for reporting this.

**Comment by mrinalwadhwa** [comment]
If you're interested in fixing the problem in a PR, we'd welcome it!!

**Comment by Ippolito72** [comment]
I think I identified the problem but would like to confirm next steps to fix it: 

[Contact Main Actions file](https://github.com/build-trust/ockam-website/blob/develop/src/views/contact/ContactMainActions/ContactMainActions.tsx)

The documentation action card is using the blog path:

`    title: 'Documentation',
    icon: DocsIcon,
    text: 'Check out our documentation pages for an introduction, or for a deep dive into how Ockam works!',
    link: {
      **### href: BLOG_PATH,**
      text: 'docs.ockam.io',`

In the [Paths file](https://github.com/build-trust/ockam-website/blob/develop/src/consts/paths.ts) there is no documentation path:

`export const HOME_PATH = '/';
export const TEAM_PATH = '/team';
export const MISSION_AND_VISION_PATH = '/mission';
export const BLOG_PATH = '/blog';
export const OPEN_ROLES_PATH = `${TEAM_PATH}#open-roles`;
export const OPEN_ROLE_PATH = '/team';
export const CONTACT_PAGE_PATH = '/contact';
export const CONTACT_FORM_PATH = `${CONTACT_PAGE_PATH}/form`;`

Should a new path be created for the Docs? Or simply replace the blog path with the https://docs.ockam.io/ link


FYI this is Nick, and it will be my first PR so I'm new to the process.
