### ISSUE TITLE
reCaptcha key issue on Contact form

### ISSUE THREAD

**Issue by paulgrehan** [build-trust/ockam-website#598]
Hi, Your contact form has a key error for reCaptcha - this is preevnting anyone (myself included) from submitting requests for 1:1 contact for your new product (Orchestrator)

URI : https://ockam.io/contact/form

reCaptcha call : https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LeqW04hAAAAAGAHmYY_4JLipXC8iko2mwy2Poz4&co=aHR0cHM6Ly93d3cub2NrYW0uaW86NDQz&hl=en-GB&type=image&v=PRMRaAwB3KlylGQR57Dyk-pF&theme=light&size=normal&badge=bottomright&cb=99b2ggn812pv

![image](https://user-images.githubusercontent.com/99773940/185282009-b64555cd-f611-40ca-b4f2-8765bbe8c518.png)

**Comment by mrinalwadhwa** [comment]
@paulgrehan thank you for reporting this. We'll fix this soon.
In the meantime you can reach me on `mrinal@ockam.io` if your questions.
