### ISSUE TITLE
Create a right navigation column on blog pages

### ISSUE THREAD

**Issue by mattgreg** [build-trust/ockam-website#611]
<img width="215" alt="Screen Shot 2022-09-06 at 5 07 20 PM" src="https://user-images.githubusercontent.com/27310398/188760999-81467ff0-652d-44df-89eb-ae38eedda34f.png">

The blog text should be left justified to make space for a right navigation column.

This column should have a link to the blog post on GitHub #609 
And use the H2, H3, H4 to create and text outline and links to anchors.

It should work like GitBook.
https://docs.ockam.io/get-started

**Comment by lukasztucholski** [comment]
PR: https://github.com/build-trust/ockam-website/pull/634
