### ISSUE TITLE
job postings with expired links need a different redirect

### ISSUE THREAD

**Issue by mattgreg** [build-trust/ockam-website#616]
A common flow is that our job descriptions will change or be reposted. When this happens a new URL is generate on our website.

Since we post JDs all over the internet, it's possible that a URL will expire if it's a couple of weeks old. If a URL doesn't exist anymore, We want to redirect any url  with the format: `https://www.ockam.io/team/<a job name>/<long alphanumeric ID>` to `https://www.ockam.io/team#open-roles`. Right now all redirects go to `ockam.io`

**Comment by lukasztucholski** [comment]
Done and merged into develop

**Comment by mattgreg** [comment]
Thanks!
