### ISSUE TITLE
create url/link anchors that filter the team list

### ISSUE THREAD

**Issue by mattgreg** [build-trust/ockam-website#630]
On the bottom of the https://www.ockam.io/mission page, there is a roster of `whos on the team`. When the user selects a group (ie all, full time, board of directors, advisors) in the left menu, then the roster is filtered for that group.

We need to have the following anchors created so that the page scrolls down to the team section, and selects the group associated with that anchor. 

/mission**#all**
/mission**#full_time**
/mission**#board**
/mission**#advisors**

**Comment by lukasztucholski** [comment]
Here is PR
https://github.com/build-trust/ockam-website/pull/633

**Comment by mattgreg** [comment]
@lukasztucholski when these issues land, can you close the issue?
