### ISSUE TITLE
Broken link on contact page

### ISSUE THREAD

**Issue by mattgreg** [build-trust/ockam-website#656]
The `Let's build` link on https://www.ockam.io/contact has a broken link.

The new link should be https://docs.ockam.io/use-cases

**Comment by lukasztucholski** [comment]
@mattgreg Same link are in two others sections on website. It still be same in there or maybe change to another? 
> in footer in "Build a Demo" button
> in "Builders" card in section "Trust for Data-in-Motion" on homepage

PR: https://github.com/build-trust/ockam-website/pull/661

**Comment by mattgreg** [comment]
Yes - good catch @lukasztucholski all three need to be updated to https://docs.ockam.io/use-cases. 

Thanks for catching that. Can you make the update?
