### ISSUE TITLE
Setup dependabot to update dependencies

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam-website#851]
We should setup dependabot to update dependencies in this repository, we should update dependencies daily. Documentation on setting up dependabot can be found here https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#example-dependabotyml-file

**Comment by engineerakki** [comment]
I can work on this.

**Comment by nazmulidris** [comment]
@engineerakki That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by metaclips** [comment]
Closed by https://github.com/build-trust/ockam-website/pull/860. Thanks @engineerakki
