### ISSUE TITLE
Check for lint errors in repository on pull and push request

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam-website#852]
Replicate [lint workflow that we use in the ockam repository](https://github.com/build-trust/ockam/blob/eae2711d8d608f415e474ab203a6bb2654dd46d4/.github/workflows/all.yml#L299) which ensures that files adhere to a fixed coding style

**Comment by frantic-rabbit** [comment]
Hey @metaclips, i tried to solve the issue but how can i check  if my code is working properly or not?

**Comment by metaclips** [comment]
Hello @frantic-rabbit checking-in, do you need any help on getting this to be closed?, you can also join us on the contributors discord channel https://discord.gg/bewvnm6zqS

**Comment by engineerakki** [comment]
Is this still up for grabs ?
I can do it if @frantic-rabbit is not having bandwidth

**Comment by metaclips** [comment]
Hello @engineerakki, I’ll be assigning this issue to you now

**Comment by metaclips** [comment]
closed by https://github.com/build-trust/ockam-website/pull/860
